#!/usr/bin/env python
from collections import Counter


items = []
while True:
    try:
        line = input().strip()
        if line:
            items.append(line)
        else:
            break
    except (EOFError):
        break


class Policy:
    def __init__(self, stringified):
        min_max, self.letter = stringified.split()
        self.min, self.max = (int(i) for i in min_max.split("-"))

    def matches(self, password):
        count = Counter(password).get(self.letter, 0)
        return self.min <= count <= self.max


valid = []
for line in items:
    policy, password = line.split(": ")
    policy = Policy(policy)
    if policy.matches(password):
        valid.append(password)
print(len(valid))
