#!/usr/bin/env python
from collections import Counter


items = []
while True:
    try:
        line = input().strip()
        if line:
            items.append(line)
        else:
            break
    except (EOFError):
        break


class Policy:
    def __init__(self, stringified):
        first_second, self.letter = stringified.split()
        self.first, self.second = (int(i) for i in first_second.split("-"))

    # Exactly one of these positions must contain letter!
    def matches(self, password):
        count = 0
        if len(password) >= self.first:
            count += self.letter == password[self.first - 1]
        if len(password) >= self.second:
            count += self.letter == password[self.second - 1]
        return count == 1


valid = []
for line in items:
    policy, password = line.split(": ")
    policy = Policy(policy)
    if policy.matches(password):
        valid.append(password)
print(len(valid))
