#!/usr/bin/env python

required_fields = [
    "byr",  # (Birth Year)
    "iyr",  # (Issue Year)
    "eyr",  # (Expiration Year)
    "hgt",  # (Height)
    "hcl",  # (Hair Color)
    "ecl",  # (Eye Color)
    "pid",  # (Passport ID)
    # "cid",  # (Country ID)
]

data = """ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in
""".splitlines()

data = None

if not data:
    lines = []
    print("Enter the data: ")
    # We need to allow a single blank line here...
    # maybe should have gone with shell arguments...
    blanks_in_seq = 0
    while True:
        try:
            line = input().strip()
            if line:
                lines.append(line)
                blanks_in_seq = 0
            elif blanks_in_seq == 0:
                lines.append(line)
                blanks_in_seq += 1
            else:
                break
        except (EOFError):
            break
    data = lines


def passports(data):
    passport_lines = []
    for line in data:
        # print(line)
        if line:
            passport_lines.append(line)
        else:
            yield " ".join(passport_lines)
            passport_lines = []
    if len(passport_lines):  # ignore blank line at end
        yield " ".join(passport_lines)


def is_valid(passport_line):
    fields = dict([pair.split(":") for pair in passport_line.split()])
    for field in required_fields:
        if field not in fields:
            return False
    return True


print(sum(is_valid(passport) for passport in passports(data)))
