#!/usr/bin/env python
from collections import defaultdict
import doctest


# Part One


def run(starting_numbers, final_turn):
    r"""
    >>> run([0, 3, 6], 2020)
    436
    >>> run([1, 3, 2], 2020)
    1
    >>> run([2, 1, 3], 2020)
    10
    >>> run([1, 2, 3], 2020)
    27
    >>> run([2, 3, 1], 2020)
    78
    >>> run([3, 2, 1], 2020)
    438
    >>> run([3, 1, 2], 2020)
    1836
    """
    history = defaultdict(list)
    turn = 0
    result = None
    while turn < final_turn:
        turn += 1
        if starting_numbers:
            result = starting_numbers.pop(0)
        else:
            turns = history[result]
            result = 0 if len(turns) == 1 else turns[-1] - turns[-2]
        history[result].append(turn)
        # print(f"{turn} {result}")
    return result


# Part Two


def main():
    print("Part One")
    print(run([1, 2, 16, 19, 18, 0], 2020))

    print("Part Two")
    assert run([0, 3, 6], 30000000) == 175594
    assert run([1, 3, 2], 30000000) == 2578
    assert run([2, 1, 3], 30000000) == 3544142
    assert run([1, 2, 3], 30000000) == 261214
    assert run([2, 3, 1], 30000000) == 6895259
    assert run([3, 2, 1], 30000000) == 18
    assert run([3, 1, 2], 30000000) == 362
    print(run([1, 2, 16, 19, 18, 0], 30000000))


if __name__ == "__main__":
    doctest.testmod()
    main()
